#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: ./scripts/override environment=Q1 disable_pin_request=true"
  exit 1
fi
f=app/src/main/assets/override.properties
echo -n '' > $f
for o in $@
do
  echo $o >> $f
done
echo '' >> $f

